# https://taskfile.dev
version: '3'

vars:
  VENV: .venv
  PY: '{{.VENV}}/bin/python'
  PIP: '{{.VENV}}/bin/pip'
  DEPS_STAMP: '{{.VENV}}/.deps_stamp'
  MODEL_FILE: '{{default "models/google_medgemma-4b-it-Q4_K_M.gguf" .MODEL_FILE}}'

tasks:
  venv:
    desc: Create local virtualenv
    status:
      - test -x {{.PY}}
    cmds:
      - python3 -m venv {{.VENV}}
      - "{{.PIP}} install -U pip"

  deps:
    desc: Install project (editable) into venv
    deps: [venv]
    status:
      - test -f {{.DEPS_STAMP}} && test {{.DEPS_STAMP}} -nt pyproject.toml
    cmds:
      - "{{.PIP}} install -e ."
      - "date > {{.DEPS_STAMP}}"

  model:
    desc: Download MedGemma GGUF model from HuggingFace
    deps: [deps]
    status:
      - test -f {{.MODEL_FILE}}
    cmds:
      - mkdir -p models
      - "{{.PY}} -m huggingface_hub.commands.huggingface_cli download google/medgemma-4b-it-gguf google_medgemma-4b-it-Q4_K_M.gguf --local-dir models/"

  run:
    desc: "Run pipeline on one case (env: CASE, OUT, MODE)"
    deps: [deps]
    vars:
      CASE: '{{default "cases/case_01.json" .CASE}}'
      OUT: '{{default "runs/case_01" .OUT}}'
      MODE: '{{default "baseline" .MODE}}'
    preconditions:
      - sh: '[ "{{.MODE}}" != "llm" ] || test -f {{.MODEL_FILE}}'
        msg: "Missing model file. Run: task model"
    cmds:
      - "{{.PY}} -m pa_trace run --case {{.CASE}} --out {{.OUT}} --mode {{.MODE}}"
      - 'echo "Open: {{.OUT}}/highlights.html"'
      - 'echo "Open: {{.OUT}}/packet.md"'

  eval:
    desc: "Evaluate on cases folder (env: CASES_DIR, GOLD, EVAL_OUT, MODE)"
    deps: [deps]
    vars:
      CASES_DIR: '{{default "cases" .CASES_DIR}}'
      GOLD: '{{default "cases/gold_labels.json" .GOLD}}'
      EVAL_OUT: '{{default "runs/eval" .EVAL_OUT}}'
      MODE: '{{default "baseline" .MODE}}'
    preconditions:
      - sh: '[ "{{.MODE}}" != "llm" ] || test -f {{.MODEL_FILE}}'
        msg: "Missing model file. Run: task model"
    cmds:
      - "{{.PY}} -m pa_trace eval --cases {{.CASES_DIR}} --gold {{.GOLD}} --out {{.EVAL_OUT}} --mode {{.MODE}}"
      - 'echo "Eval report: {{.EVAL_OUT}}/eval_report.md"'

  clean:
    desc: Remove run outputs
    cmds:
      - rm -rf runs
